### ISSUE TITLE
Bug for PocketGeiger: `'Manager' object has no attribute 'aes'`

### ISSUE THREAD

**Issue by bplimley** [bearing/dosenet-raspberrypi#92]
Introduced in pull request #89, I thought I was testing since then so I don't know what happened.
